title: "MiddleRaster's Pages"
description: "My thoughts on software, etc."
url: "https://middleraster.github.io"
baseurl: ""

theme: minima
header_pages:
  - TDD/tutorials.md

plugins:
  - jekyll-sitemap
